### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by DmitryDNKK** [feuvan/opencore-amr-iOS#12]
Please, either add the file compile to sources or exclude it from the line #2919
# Auxiliary files required by this configure script.
ac_aux_files="config.guess config.sub ltmain.sh compile missing install-sh"

**Comment by feuvan** [comment]
fixed in script build_ios.sh

**Comment by DmitryDNKK** [comment]
Sorry, the issue still present. The file configure line #2919.
